import { estimatedCommission, gabPriorityScore } from "@/lib/calculations";
import type { AppData, ChecklistItem, Owner, Property } from "@/lib/types";
import { checklistLabels } from "@/lib/translations";

const now = new Date().toISOString();

function property(input: Omit<Property, "estimatedCommission" | "opportunityScore" | "createdAt" | "updatedAt">): Property {
  const estimated = estimatedCommission(input.estimatedValue, input.commissionPercentage);
  return {
    ...input,
    estimatedCommission: estimated,
    opportunityScore: gabPriorityScore({ ...input, estimatedCommission: estimated }),
    createdAt: now,
    updatedAt: now,
  };
}

export const seedOwners: Owner[] = [
  {
    id: "own_ana",
    fullName: "Ana Lucia Moraes",
    cpfCnpj: "123.456.789-00",
    phone: "(19) 3232-1100",
    whatsapp: "(19) 99988-1100",
    email: "ana.moraes@example.com",
    address: "Rua Barao de Jaguara, 900, Campinas",
    mainProblem: "Inventario pendente e IPTU acumulado.",
    objections: "Receio de custos iniciais.",
    urgencyLevel: "urgent",
    lastContactDate: "2026-04-22",
    nextActionDate: "2026-05-08",
    notes: "Familia deseja vender apos regularizacao.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "own_bruno",
    fullName: "Bruno Carvalho",
    cpfCnpj: "45.987.654/0001-10",
    phone: "(19) 3884-2200",
    whatsapp: "(19) 99877-2200",
    email: "bruno@example.com",
    address: "Avenida Jose Paulino, 350, Paulinia",
    mainProblem: "Averbacao de area construida.",
    objections: "Quer entender prazo no cartorio.",
    urgencyLevel: "high",
    lastContactDate: "2026-04-25",
    nextActionDate: "2026-05-06",
    notes: "Possivel mandato exclusivo.",
    createdAt: now,
    updatedAt: now,
  },
];

export const seedProperties: Property[] = [
  property({
    id: "prop_campinas_cambui",
    ownerId: "own_ana",
    address: "Rua Conceicao, 742",
    city: "Campinas",
    neighborhood: "Cambui",
    propertyType: "Casa comercial",
    estimatedValue: 1200000,
    iptuDebt: 85000,
    regularizationEstimatedCost: 95000,
    postRegularizationValue: 1580000,
    commissionPercentage: 6,
    registryNumber: "3.245-CPS",
    cartorioStatus: "Matricula desatualizada",
    legalStatus: "Inventario em aberto",
    source: "Indicacao",
    urgencyLevel: "urgent",
    currentStatus: "analysis",
    notes: "Alto potencial para venda corporativa.",
  }),
  property({
    id: "prop_paulinia_santa_cecilia",
    ownerId: "own_bruno",
    address: "Avenida dos Expedicionarios, 1180",
    city: "Paulinia",
    neighborhood: "Santa Cecilia",
    propertyType: "Galpao",
    estimatedValue: 2400000,
    iptuDebt: 120000,
    regularizationEstimatedCost: 180000,
    postRegularizationValue: 3100000,
    commissionPercentage: 5,
    registryNumber: "8.771-PLN",
    cartorioStatus: "Pendencia de averbacao",
    legalStatus: "Sem litigio",
    source: "Prospeccao ativa",
    urgencyLevel: "high",
    currentStatus: "mandateSigned",
    notes: "Proprietario aceita antecipar documentos.",
  }),
  property({
    id: "prop_sumare_centro",
    address: "Rua Dom Barreto, 204",
    city: "Sumare",
    neighborhood: "Centro",
    propertyType: "Terreno",
    estimatedValue: 680000,
    iptuDebt: 0,
    regularizationEstimatedCost: 45000,
    postRegularizationValue: 820000,
    commissionPercentage: 6,
    registryNumber: "11.903-SMR",
    cartorioStatus: "Ok",
    legalStatus: "Zoneamento a confirmar",
    source: "Parceiro local",
    urgencyLevel: "medium",
    currentStatus: "contactStarted",
    notes: "Avaliar viabilidade para incorporadora.",
  }),
  property({
    id: "prop_hortolandia_jd_amanda",
    address: "Rua das Orquideas, 77",
    city: "Hortolandia",
    neighborhood: "Jardim Amanda",
    propertyType: "Residencial",
    estimatedValue: 390000,
    iptuDebt: 32000,
    regularizationEstimatedCost: 60000,
    postRegularizationValue: 510000,
    commissionPercentage: 6,
    registryNumber: "5.442-HRT",
    cartorioStatus: "Contrato particular",
    legalStatus: "Possivel usucapiao",
    source: "WhatsApp",
    urgencyLevel: "high",
    currentStatus: "newLead",
    notes: "Necessita triagem juridica inicial.",
  }),
  property({
    id: "prop_indaiatuba_itaici",
    address: "Estrada do Fogueteiro, 1500",
    city: "Indaiatuba",
    neighborhood: "Itaici",
    propertyType: "Chacara",
    estimatedValue: 1750000,
    iptuDebt: 44000,
    regularizationEstimatedCost: 130000,
    postRegularizationValue: 2300000,
    commissionPercentage: 5,
    registryNumber: "21.300-IND",
    cartorioStatus: "Area divergente",
    legalStatus: "Pendencia ambiental",
    source: "Engenharia parceira",
    urgencyLevel: "medium",
    currentStatus: "regularization",
    notes: "Mapear pendencias ambientais antes da oferta.",
  }),
  property({
    id: "prop_valinhos_vila_santana",
    address: "Rua Treze de Maio, 64",
    city: "Valinhos",
    neighborhood: "Vila Santana",
    propertyType: "Sobrado",
    estimatedValue: 890000,
    iptuDebt: 71000,
    regularizationEstimatedCost: 70000,
    postRegularizationValue: 1120000,
    commissionPercentage: 6,
    registryNumber: "14.882-VLN",
    cartorioStatus: "Certidao de onus pendente",
    legalStatus: "Debitos fiscais",
    source: "Campanha",
    urgencyLevel: "urgent",
    currentStatus: "meetingScheduled",
    notes: "Reuniao com herdeiros agendada.",
  }),
];

export const publicSourcingCases: Property[] = [
  property({
    id: "public_gleba_003_gl_rem",
    address: "Rua Valentim dos Santos Carvalho - Gleba-003-GL-REM",
    city: "Campinas",
    neighborhood: "Sousas / Joaquim Egidio",
    propertyType: "Loteamento clandestino",
    estimatedValue: 0,
    iptuDebt: 0,
    regularizationEstimatedCost: 0,
    postRegularizationValue: 0,
    commissionPercentage: 6,
    registryNumber: "A confirmar",
    cartorioStatus: "A confirmar",
    legalStatus: "Multa e embargo administrativo por parcelamento ilegal do solo",
    source: "Fonte publica - Prefeitura/Imprensa local",
    urgencyLevel: "urgent",
    currentStatus: "newLead",
    notes:
      "Caso publico citado em noticia sobre loteamentos clandestinos embargados na APA Campinas. Usar como lead territorial, sem dados pessoais. Validar situacao atual no Diario Oficial, Urbanismo e cartorio antes de contato comercial.",
  }),
  property({
    id: "public_nova_cachoeira",
    address: "CAM 120, acesso via Rua Professora Lydia Abdalla - Nova Cachoeira",
    city: "Campinas",
    neighborhood: "Sousas / Joaquim Egidio",
    propertyType: "Loteamento clandestino",
    estimatedValue: 0,
    iptuDebt: 0,
    regularizationEstimatedCost: 0,
    postRegularizationValue: 0,
    commissionPercentage: 6,
    registryNumber: "A confirmar",
    cartorioStatus: "A confirmar",
    legalStatus: "Multas, embargo e Acao Civil Publica informada em fonte publica",
    source: "Fonte publica - Prefeitura/Imprensa local",
    urgencyLevel: "urgent",
    currentStatus: "newLead",
    notes:
      "Caso publico conhecido como Nova Cachoeira. Nao abordar compradores finais sem validacao juridica. Primeiro passo: mapear associacao, processo, restricoes ambientais e legitimidade de eventual regularizacao.",
  }),
  property({
    id: "public_sitio_recanto_verde",
    address: "Acesso pela Rodovia Jose Bonifacio Coutinho Nogueira SP-081 - Sitio Recanto Verde / Vila Natureza",
    city: "Campinas",
    neighborhood: "Sousas / Joaquim Egidio",
    propertyType: "Ocupacao/loteamento em APA",
    estimatedValue: 0,
    iptuDebt: 0,
    regularizationEstimatedCost: 0,
    postRegularizationValue: 0,
    commissionPercentage: 6,
    registryNumber: "A confirmar",
    cartorioStatus: "A confirmar",
    legalStatus: "Multa e embargo administrativo informados em fonte publica",
    source: "Fonte publica - Prefeitura/Imprensa local",
    urgencyLevel: "urgent",
    currentStatus: "newLead",
    notes:
      "Caso publico conhecido como Sitio Recanto Verde ou Vila Natureza. Alto risco ambiental/urbanistico; tratar como inteligencia de mercado e nao como promessa de regularizacao.",
  }),
  property({
    id: "public_colinas_capricornio",
    address: "Estrada do Capricornio CAM 245 - Clube de Campo Colinas do Capricornio",
    city: "Campinas",
    neighborhood: "Sousas / Joaquim Egidio",
    propertyType: "Loteamento em APA",
    estimatedValue: 0,
    iptuDebt: 0,
    regularizationEstimatedCost: 0,
    postRegularizationValue: 0,
    commissionPercentage: 6,
    registryNumber: "A confirmar",
    cartorioStatus: "A confirmar",
    legalStatus: "Multas, embargo e Acao Cautelar informada em fonte publica",
    source: "Fonte publica - Prefeitura/Imprensa local",
    urgencyLevel: "urgent",
    currentStatus: "newLead",
    notes:
      "Caso publico citado como Clube de Campo Colinas do Capricornio. Prioridade de analise: risco judicial, ambiental e possibilidade real de servico tecnico consultivo.",
  }),
  property({
    id: "public_ecoville_clube",
    address: "Rua Rubens Gomes Balsas - Ecoville Clube",
    city: "Campinas",
    neighborhood: "Sousas / Joaquim Egidio",
    propertyType: "Loteamento clandestino",
    estimatedValue: 0,
    iptuDebt: 0,
    regularizationEstimatedCost: 0,
    postRegularizationValue: 0,
    commissionPercentage: 6,
    registryNumber: "A confirmar",
    cartorioStatus: "A confirmar",
    legalStatus: "Multa e embargo por ilegalidade da ocupacao",
    source: "Fonte publica - Prefeitura/Imprensa local",
    urgencyLevel: "urgent",
    currentStatus: "newLead",
    notes:
      "Caso publico denominado Ecoville Clube. Tratar como lead territorial para diagnostico e relacionamento institucional.",
  }),
  property({
    id: "public_lc492_dic",
    address: "Regiao dos DICs - Programa LC 492/2024",
    city: "Campinas",
    neighborhood: "DICs",
    propertyType: "Conjunto habitacional / construcao irregular",
    estimatedValue: 0,
    iptuDebt: 0,
    regularizationEstimatedCost: 0,
    postRegularizationValue: 0,
    commissionPercentage: 6,
    registryNumber: "A confirmar",
    cartorioStatus: "A confirmar",
    legalStatus: "Potencial enquadramento em programa de regularizacao social de construcoes irregulares",
    source: "Fonte publica - LC 492/2024",
    urgencyLevel: "high",
    currentStatus: "newLead",
    notes:
      "Zona/bairro citado em fontes publicas sobre a LC 492/2024. Oportunidade de campanha educativa e triagem individual autorizada pelos moradores.",
  }),
  property({
    id: "public_lc492_padre_anchieta",
    address: "Regiao Padre Anchieta - Programa LC 492/2024",
    city: "Campinas",
    neighborhood: "Padre Anchieta",
    propertyType: "Conjunto habitacional / construcao irregular",
    estimatedValue: 0,
    iptuDebt: 0,
    regularizationEstimatedCost: 0,
    postRegularizationValue: 0,
    commissionPercentage: 6,
    registryNumber: "A confirmar",
    cartorioStatus: "A confirmar",
    legalStatus: "Potencial enquadramento em programa de regularizacao social de construcoes irregulares",
    source: "Fonte publica - LC 492/2024",
    urgencyLevel: "high",
    currentStatus: "newLead",
    notes:
      "Zona/bairro citado em fontes publicas sobre a LC 492/2024. Validar loteamento contemplado e documentacao exigida antes de proposta.",
  }),
  property({
    id: "public_lc492_jardim_bassoli",
    address: "Residencial/Jardim Bassoli - Programa LC 492/2024",
    city: "Campinas",
    neighborhood: "Jardim Bassoli",
    propertyType: "Conjunto habitacional / construcao irregular",
    estimatedValue: 0,
    iptuDebt: 0,
    regularizationEstimatedCost: 0,
    postRegularizationValue: 0,
    commissionPercentage: 6,
    registryNumber: "A confirmar",
    cartorioStatus: "A confirmar",
    legalStatus: "Potencial enquadramento em programa de regularizacao social de construcoes irregulares",
    source: "Fonte publica - LC 492/2024",
    urgencyLevel: "high",
    currentStatus: "newLead",
    notes:
      "Zona/bairro citado em fontes publicas sobre a LC 492/2024. Bom caso para prospeccao via associacao, sindicos e liderancas locais.",
  }),
];

const seedChecklist: ChecklistItem[] = seedProperties.flatMap((item) =>
  checklistLabels.slice(0, 5).map((label, index) => ({
    id: `chk_${item.id}_${index}`,
    propertyId: item.id,
    label,
    status: index < 2 ? "done" : index === 2 ? "inProgress" : "pending",
    responsible: index < 2 ? "Equipe juridica" : "GAB Engenharia",
    dueDate: `2026-05-${String(10 + index).padStart(2, "0")}`,
    notes: "",
  })),
);

export const seedData: AppData = {
  properties: seedProperties,
  owners: seedOwners,
  documents: [
    {
      id: "doc_1",
      propertyId: "prop_campinas_cambui",
      name: "Matricula inicial",
      type: "Matricula",
      fileUrl: "/documentos/matricula-cambui.pdf",
      uploadDate: "2026-04-20",
      notes: "Solicitar segunda via atualizada.",
    },
  ],
  checklist: seedChecklist,
  activities: [
    {
      id: "act_1",
      propertyId: "prop_campinas_cambui",
      ownerId: "own_ana",
      date: "2026-04-22",
      type: "call",
      summary: "Contato inicial sobre inventario e debitos.",
      nextStep: "Enviar proposta de regularizacao.",
      responsible: "Comercial GAB",
    },
  ],
};
